### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by avebest1992** [EEEugene/StepNumberChangeSNC#1]
部署云函数的时候点击测试，显示失败，应该怎么操作呢？（代码仅修改了用户名密码等参数）
`
{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 696, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 677, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 728, in exec_module\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 3, in &lt;module;&gt;\n    import requests,time,re,json,random\nModuleNotFoundError: No module named 'requests'","requestId":"76121d9f-2051-45fd-91fa-cb3a9f86b0f9","statusCode":443}
`

**Comment by EEEugene** [comment]
有点奇怪，理论上来说代码是没问题的，我重新上传一个代码你再试试

**Comment by EEEugene** [comment]
我上传了一个压缩包，你下载那里面的代码测试一下试试

**Comment by avebest1992** [comment]
> 我上传了一个压缩包，你下载那里面的代码测试一下试试

测试成功了，原因可能是python解释器版本，默认是3.7.4，改成3.6可以了

运行环境	Python 3.6

**Comment by EEEugene** [comment]
原来是python问题，哈哈哈，小问题
