### ISSUE TITLE
函数登录小米运动失败，步数不生效！

### ISSUE THREAD

**Issue by lzyang187** [EEEugene/StepNumberChangeSNC#11]
没有生效呢，小米运动改版为Zepp Life，我安装的Android版本号为：6.5.5

运行函数输出：
Invoke function helloworld-1678107449 [RequestId:361bf236-ae84-40d0-93ef-a40980ac4c5f]
Response: 
null
Output:
START RequestId: 361bf236-ae84-40d0-93ef-a40980ac4c5f
Event RequestId: 361bf236-ae84-40d0-93ef-a40980ac4c5f
已设置为随机步数（20000-29999）
Starting new HTTPS connection (1): api-user.huami.com:443
https://api-user.huami.com:443 "POST /registrations/1111111@qq.com/tokens HTTP/1.1" 303 0
登陆失败

**Comment by EEEugene** [comment]
你这账号就是111111@qq.com？这个不对吧，他显示登陆失败，压根没同步上去

**Comment by lzyang187** [comment]
> 

不是111111，是我占位的，实际用app登录成功的是真正的qq邮箱

**Comment by EEEugene** [comment]
总体他就是没登陆上去，显示登陆失败，检查账号密码

**Comment by lzyang187** [comment]
> 总体他就是没登陆上去，显示登陆失败，检查账号密码

检查好几遍了的，应该没问题的呢

**Comment by EEEugene** [comment]
那我也不知道了，没法解决，我这边只能排除代码问题

**Comment by EEEugene** [comment]
> > 那我也不知道了，没法解决，我这边只能排除代码问题
> 
> 已经试过了，邮箱登录不能同步，但手机号可以....

那你用的肯定不是我的代码，我的代码已经把手机登录给删除了，现在我的代码只能用邮箱登录，填手机号直接出错

**Comment by EASTINK** [comment]
> > > 那我也不知道了，没法解决，我这边只能排除代码问题
> > 
> > 
> > 已经试过了，邮箱登录不能同步，但手机号可以....
> 
> 那你用的肯定不是我的代码，我的代码已经把手机登录给删除了，现在我的代码只能用邮箱登录，填手机号直接出错

手机号出错是因为账户填错了，手机号前加上+86就可以了

**Comment by EASTINK** [comment]
![image](https://user-images.githubusercontent.com/63509561/223457071-505066e1-d1b3-475e-bf40-573a096a43f2.png)

**Comment by EEEugene** [comment]
> > > > 那我也不知道了，没法解决，我这边只能排除代码问题
> > > 
> > > 
> > > 已经试过了，邮箱登录不能同步，但手机号可以....
> > 
> > 
> > 那你用的肯定不是我的代码，我的代码已经把手机登录给删除了，现在我的代码只能用邮箱登录，填手机号直接出错
> 
> 手机号出错是因为账户填错了，手机号前加上+86就可以了

能用就行了，其次这也证明了我代码没问题，还有问题的话自己找找别的原因

**Comment by EASTINK** [comment]
> > > > > 那我也不知道了，没法解决，我这边只能排除代码问题
> > > > 
> > > > 
> > > > 已经试过了，邮箱登录不能同步，但手机号可以....
> > > 
> > > 
> > > 那你用的肯定不是我的代码，我的代码已经把手机登录给删除了，现在我的代码只能用邮箱登录，填手机号直接出错
> > 
> > 
> > 手机号出错是因为账户填错了，手机号前加上+86就可以了
> 
> 能用就行了，其次这也证明了我代码没问题，还有问题的话自己找找别的原因

我这不就是来问问看邮箱登录没有用是因为什么么？

**Comment by EEEugene** [comment]
我这边使用邮箱是没问题的，不太理解你为什么手机号可以，可能是代码换了接口的原因，不太了解

**Comment by EEEugene** [comment]
> > > > > > 那我也不知道了，没法解决，我这边只能排除代码问题
> > > > > 
> > > > > 
> > > > > 已经试过了，邮箱登录不能同步，但手机号可以....
> > > > 
> > > > 
> > > > 那你用的肯定不是我的代码，我的代码已经把手机登录给删除了，现在我的代码只能用邮箱登录，填手机号直接出错
> > > 
> > > 
> > > 手机号出错是因为账户填错了，手机号前加上+86就可以了
> > 
> > 
> > 能用就行了，其次这也证明了我代码没问题，还有问题的话自己找找别的原因
> 
> 我这不就是来问问看邮箱登录没有用是因为什么么？

我这边使用邮箱没问题，不知道具体情况，可能是换了接口原因所以手机也可以了，但前几天的情况确实是手机号不行

**Comment by EndyZhou** [comment]
我刚刚尝试邮箱登陆。api提交成功 但是步数没有更新

**Comment by lzyang187** [comment]
> 我刚刚尝试邮箱登陆。api提交成功 但是步数没有更新

贴下输出Log看看呗，我的是qq邮箱，密码是小写字母+数字，登录失败

**Comment by EndyZhou** [comment]
> > 我刚刚尝试邮箱登陆。api提交成功 但是步数没有更新
> 
> 贴下输出Log看看呗，我的是qq邮箱，密码是小写字母+数字，登录失败

4784****.com: [2023-03-08 18:16:28] 修改步数（5000）success


Telegram推送的tg_bot_token或者tg_user_id未设置!!
取消推送

**Comment by EEEugene** [comment]
<img src="https://sszblog.oss-cn-shenzhen.aliyuncs.com/img/success.png" >

这个正确输出，我也是qq邮箱，然后就同步过去了

**Comment by EndyZhou** [comment]
> ![](https://camo.githubusercontent.com/583d97de0264de405b723358abdec855d6148edc0fdb0c23a6a8e48769aed1b1/68747470733a2f2f73737a626c6f672e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f696d672f737563636573732e706e67)
> 
> 这个正确输出，我也是qq邮箱，然后就同步过去了

我log 应该是正确的吧？ 我也是新建的邮箱账号 api 成功  但是数据没有同步到微信（ 我直接跑py  和这个应该没有关系吧）
