### ISSUE TITLE
是不是邮箱也失效了啊

### ISSUE THREAD

**Issue by gushiyu01** [EEEugene/StepNumberChangeSNC#13]
我这用邮箱注册，绑定微信关注公众号后，虽然代码提示的是成功，而且接口返回也是成功的 {'code': 1, 'message': 'success'} 但是步数并没有同步到微信运动步数

**Comment by EEEugene** [comment]
邮箱正常，没有失效，我今天都是正常使用，有问题可以看看之前关的issue，那下面有些人写了自己的没同步后的解决过程

**Comment by gushiyu01** [comment]
> 看其他的issue，那个用你的代码输入+86手机号，我试了，能改成功。邮箱就是不行。

**Comment by EEEugene** [comment]
> 

有些是这样，具体原因不清楚，能用就好

**Comment by gushiyu01** [comment]
嗯嗯，是的，又能用了
