### ISSUE TITLE
不生效

### ISSUE THREAD

**Issue by flyhelanman** [EEEugene/StepNumberChangeSNC#14]
2023-03-15使用邮箱登录，程序运行成功，但是微信运动未修改成功。
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18319435/225261906-0e48bb24-54b9-48bc-ae48-9bc0002fe345.png">

**Comment by flyhelanman** [comment]
我参考了这个issues
[](https://github.com/EEEugene/StepNumberChangeSNC/issues/12)
进行了如下操作：
1、先在微信取消关注
2、在小程序一键注销并注册
3、登录app选择第三方接入绑定微信
4、在小程序输入步数同步成功，同时微信运动也同步同步成功。
最后我又测试了阿里云的云函数，但是还是没生效。

**Comment by EEEugene** [comment]
换手机号试试，前面加个+86
