### ISSUE TITLE
改成邮箱登陆，运行没反应也没提示。

### ISSUE THREAD

**Issue by taichao1** [EEEugene/StepNumberChangeSNC#16]
我在用户名和账号那里填写邮箱账号，运行后没反应额。

**Comment by abcde51111** [comment]
没收到推送？我可以收到推送，但是支付宝和小米健康 哪里步数没变。

**Comment by EEEugene** [comment]
最近工作忙，看看以前的issue有没有解决方法吧，这个代码太多人不一样的问题了

**Comment by liubos** [comment]
可以绕过微信的检测吗，小米运动步数变了但是微信运动变不了

**Comment by EEEugene** [comment]
> 

应该不行把，感觉还是没绑定好，估计是哪里还有问题，耐心找找
