### ISSUE TITLE
登录接口报错了，返回303

### ISSUE THREAD

**Issue by fzyejy** [EEEugene/StepNumberChangeSNC#17]
登录接口报错了，返回303
reason:'See Other'

**Comment by EEEugene** [comment]
检查自己问题，我刚刚测试过，正常运行

****.com: [2023-06-11 05:27:40] 修改步数（19974）success

**Comment by fzyejy** [comment]
不好意思 我描述有误，r1.headers["Location"] 是 'https://s3-us-west-2.amazonaws.com/hm-registration/successsignin.html?error=401&region=cn-northwest-1' 好像认证失败？

**Comment by zqx654033799** [comment]
我也是 授权失败，好奇怪

**Comment by LiaoGuoYin** [comment]
我也是接口 303，感觉是注册的用户无法登录

没找到华米的文档，不然可以手动看一下 API
