### ISSUE TITLE
阿里云免费额度

### ISSUE THREAD

**Issue by Angelia-Wang** [EEEugene/StepNumberChangeSNC#19]
阿里云的免费额度也变成前三个月享了😭

![image](https://github.com/EEEugene/StepNumberChangeSNC/assets/61470228/1b63b430-467d-4c54-b6b2-624c5d215fd3)

**Comment by EEEugene** [comment]
有免费额度够用的，我到现在用那么久没付费过，每天就调用那么一下，没多少的
