### ISSUE TITLE
Telegram推送的tg_bot_token或者tg_user_id未设置!!

### ISSUE THREAD

**Issue by TLLord** [EEEugene/StepNumberChangeSNC#2]
![image](https://user-images.githubusercontent.com/50732352/162650005-7e91e14e-d4e8-454a-a58f-bca25fa83869.png)
如上图，这是什么问题，麻烦帮忙看看，谢谢

**Comment by TLLord** [comment]
已解决，多谢

**Comment by EEEugene** [comment]
解决了就好
