### ISSUE TITLE
zepp life同步失败

### ISSUE THREAD

**Issue by frallisland** [EEEugene/StepNumberChangeSNC#21]
账号密码正确显示同步成功，但是zepp life都同步不上去。

**Comment by EEEugene** [comment]
目前项目是可以正常使用的，检查一下其他问题，或者可以翻一下以前的issue

**Comment by zhiqiangss** [comment]
不行了老大，邮箱反复折腾多次，全部失败。

**Comment by EEEugene** [comment]
> 不行了老大，邮箱反复折腾多次，全部失败。

231005实测，可以正常使用哈，自行翻一下之前的issue寻找没同步成功的原因。

**Comment by ip9916** [comment]
去微信搜索“满目云”，刷步数一次。之后就可以用此处的代码刷了。
一直很奇怪，首次刷的时候只有满目云是%成功的，感觉很厉害的。

**Comment by EEEugene** [comment]
> 去微信搜索“满目云”，刷步数一次。之后就可以用此处的代码刷了。 一直很奇怪，首次刷的时候只有满目云是%成功的，感觉很厉害的。

后续能用就好，如果有无法使用的朋友的话可以参考一下这个方法，我也暂时不太清楚别的软件的写法。
