### ISSUE TITLE
云函数运行报错日志

### ISSUE THREAD

**Issue by haishen668** [EEEugene/StepNumberChangeSNC#23]
python环境3.7 使用腾讯云函数
日志如下
START RequestId:c464b277-629e-45e1-86e0-30df75569d98

ERROR RequestId:c464b277-629e-45e1-86e0-30df75569d98 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 696, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 677, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 728, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 3, in \u003cmodule\u003e\n    import requests,time,re,json,random\nModuleNotFoundError: No module named 'requests'","statusCode":443}

END RequestId:c464b277-629e-45e1-86e0-30df75569d98

Report RequestId:c464b277-629e-45e1-86e0-30df75569d98 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by EEEugene** [comment]
python3.7版本不行，换3.6试试

**Comment by haishen668** [comment]
好的好的，麻烦你了
