### ISSUE TITLE
麻烦作者看看，是哪里出问题了？

### ISSUE THREAD

**Issue by ip9916** [EEEugene/StepNumberChangeSNC#25]
您好，首先感谢作者您提供了这么一个好的刷步办法。
我从7月左右一直在用您的代码，半年了都很顺利，但昨天发现没有预料中的步数（定时，阿里云，以前当然也有发生，但可以手动进网页执行一下测试代码，一般都能有步数了），于是手动测试代码，虽然提示代码成功，但步数未见实时刷新，延迟一段时间支付宝才看到步数（支付宝一般都是实时能看到）。今天又发现未有步数，于是进网页测试代码，报错。再试仍报错。后来我进华为云试，报错代码与阿里云一样。现附上报错处（3处）：
push += main(user_list[line], passwd_list[line], step) + '\\n'
app_token = get_app_token(login_token)
app_token = response['token_info']['app_token']
感觉有点不知所措，不知道怎么办才好，毕竟几个月都顺风顺水的，如果真是用不成了，那该怎么办啊

**Comment by lhbill** [comment]
我的也报错了，之前用了很长时间都没问题
使用的是阿里云，好像是阿里云的函数功能升级了
日志如下，供参考
2024-02-02 13:47:43FC Invoke Start RequestId: 1-65bc81ff-15b79ac1-8dcfb4446ba0
2024-02-02 13:47:43已设置为随机步数（20000-29999）
2024-02-02 13:47:452024-02-02 13:47:45 1-65bc81ff-15b79ac1-8dcfb4446ba0 [ERROR] {
    "errorMessage": "'token_info'",
    "errorType": "KeyError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 170",
            "in main_handler",
            "push += main(user_list[line], passwd_list[line], step) + '\\n'"
        ],
        [
            "File \"/code/index.py\"",
            "line 105",
            "in main",
            "app_token = get_app_token(login_token)"
        ],
        [
            "File \"/code/index.py\"",
            "line 146",
            "in get_app_token",
            "app_token = response['token_info']['app_token']"
        ]
    ]
}
2024-02-02 13:47:45FC Invoke End RequestId: 1-65bc81ff-15b79ac1-8dcfb4446ba0, Error: Unhandled function error

**Comment by EEEugene** [comment]
现在再跑代码试一下，我刚刚测试是可以正常使用，步数也有。

**Comment by ip9916** [comment]
嗯，试了果然又好使了。

**Comment by EEEugene** [comment]
没有什么问题的话我这边先关闭这个issues了
