### ISSUE TITLE
请问zepp life可以用吗？

### ISSUE THREAD

**Issue by junjie319** [EEEugene/StepNumberChangeSNC#27]
小米运动现在关闭了三方接口，请问这个脚本zepp life可以用吗？

**Comment by SheffieldXie** [comment]
这个脚本现在好像用不了了

**Comment by lhbill** [comment]
我的脚步也有一段时间不能用了，无法跟新步数，不知道有没有更新的脚本？

**Comment by iChoix** [comment]
9月18日以后就再也没有成功过了 一直是挂在阿里云的。测试错误如下：
{
    "errorMessage": "HTTPConnectionPool(host='api.m.taobao.com', port=80): Max retries exceeded with url: /rest/api3.do?api=mtop.common.getTimestamp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07db8cb550>: Failed to establish a new connection: [Errno 111] Connection refused',))",
    "errorType": "ConnectionError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 170",
            "in main_handler",
            "push += main(user_list[line], passwd_list[line], step) + '\\n'"
        ],
        [
            "File \"/code/index.py\"",
            "line 103",
            "in main",
            "t = get_time()"
        ],
        [
            "File \"/code/index.py\"",
            "line 138",
            "in get_time",
            "response = requests.get(url,headers=headers).json()"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 75",
            "in get",
            "return request('get', url, params=params, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 61",
            "in request",
            "return session.request(method=method, url=url, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 529",
            "in request",
            "resp = self.send(prep, **send_kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 645",
            "in send",
            "r = adapter.send(request, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py\"",
            "line 519",
            "in send",
            "raise ConnectionError(e, request=request)"
        ]
    ]
}

**Comment by EEEugene** [comment]
> 9月18日以后就再也没有成功过了 一直是挂在阿里云的。测试错误如下： { "errorMessage": "HTTPConnectionPool(host='api.m.taobao.com', port=80): Max retries exceeded with url: /rest/api3.do?api=mtop.common.getTimestamp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07db8cb550>: Failed to establish a new connection: [Errno 111] Connection refused',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url,headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] }

接口出错了，目前已修复，换上最新的代码试一下

**Comment by iChoix** [comment]
> > 9月18日以后就再也没有成功过了 一直是挂在阿里云的。测试错误如下： { "errorMessage": "HTTPConnectionPool(host='api.m.taobao.com', port=80): Max retries exceeded with url: /rest/api3.do?api=mtop.common.getTimestamp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07db8cb550>: Failed to establish a new connection: [Errno 111] Connection refused',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url,headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] }
> 
> 接口出错了，目前已修复，换上最新的代码试一下

按照SNC-Fix getTimeStamp API error bug修改三列代码后测试成功 感谢大大

**Comment by lhbill** [comment]
昨天开始又不能用了，挂在阿里云，报错的日志如下，供大大参考
FC Invoke Start RequestId: t-67189ef0-15924fb2-05e7b7600086
已设置为随机步数（20000-29999）
2024-10-23T07:02:11.548Z t-67189ef0-15924fb2-05e7b7600086 [ERROR] {
    "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2596c305f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",
    "errorType": "ConnectionError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 170",
            "in main_handler",
            "push += main(user_list[line], passwd_list[line], step) + '\\n'"
        ],
        [
            "File \"/code/index.py\"",
            "line 103",
            "in main",
            "t = get_time()"
        ],
        [
            "File \"/code/index.py\"",
            "line 138",
            "in get_time",
            "response = requests.get(url, headers=headers).json()"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 75",
            "in get",
            "return request('get', url, params=params, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 61",
            "in request",
            "return session.request(method=method, url=url, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 529",
            "in request",
            "resp = self.send(prep, **send_kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 645",
            "in send",
            "r = adapter.send(request, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py\"",
            "line 519",
            "in send",
            "raise ConnectionError(e, request=request)"
        ]
    ]
}
FC Invoke End RequestId: t-67189ef0-15924fb2-05e7b7600086, Error: Unhandled function error

**Comment by EEEugene** [comment]
> 昨天开始又不能用了，挂在阿里云，报错的日志如下，供大大参考 FC Invoke Start RequestId: t-67189ef0-15924fb2-05e7b7600086 已设置为随机步数（20000-29999） 2024-10-23T07:02:11.548Z t-67189ef0-15924fb2-05e7b7600086 [ERROR] { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2596c305f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] } FC Invoke End RequestId: t-67189ef0-15924fb2-05e7b7600086, Error: Unhandled function error

我这边这两天跑的都还是正常的哈，可以再去阿里云手动运行一次看看是否成功

**Comment by Sexbabe** [comment]
> > 昨天开始又不能用了，挂在阿里云，报错的日志如下，供大大参考 FC Invoke Start RequestId: t-67189ef0-15924fb2-05e7b7600086 已设置为随机步数（20000-29999） 2024-10-23T07:02:11.548Z t-67189ef0-15924fb2-05e7b7600086 [ERROR] { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2596c305f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] } FC Invoke End RequestId: t-67189ef0-15924fb2-05e7b7600086, Error: Unhandled function error
> 
> 我这边这两天跑的都还是正常的哈，可以再去阿里云手动运行一次看看是否成功

回大大 我也是同上代码错误 不知道什么情况 刚刚部署并测试的
{
    "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b702f4550>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",
    "errorType": "ConnectionError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 170",
            "in main_handler",
            "push += main(user_list[line], passwd_list[line], step) + '\\n'"
        ],
        [
            "File \"/code/index.py\"",
            "line 103",
            "in main",
            "t = get_time()"
        ],
        [
            "File \"/code/index.py\"",
            "line 138",
            "in get_time",
            "response = requests.get(url, headers=headers).json()"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 75",
            "in get",
            "return request('get', url, params=params, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py\"",
            "line 61",
            "in request",
            "return session.request(method=method, url=url, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 529",
            "in request",
            "resp = self.send(prep, **send_kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py\"",
            "line 645",
            "in send",
            "r = adapter.send(request, **kwargs)"
        ],
        [
            "File \"/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py\"",
            "line 519",
            "in send",
            "raise ConnectionError(e, request=request)"
        ]
    ]
}

**Comment by EEEugene** [comment]
> > > 昨天开始又不能用了，挂在阿里云，报错的日志如下，供大大参考 FC Invoke Start RequestId: t-67189ef0-15924fb2-05e7b7600086 已设置为随机步数（20000-29999） 2024-10-23T07:02:11.548Z t-67189ef0-15924fb2-05e7b7600086 [ERROR] { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2596c305f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] } FC Invoke End RequestId: t-67189ef0-15924fb2-05e7b7600086, Error: Unhandled function error
> > 
> > 
> > 我这边这两天跑的都还是正常的哈，可以再去阿里云手动运行一次看看是否成功
> 
> 回大大 我也是同上代码错误 不知道什么情况 刚刚部署并测试的 { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b702f4550>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] }

我今天下午6点跑了一下还是正常的哈，可以多跑几次试一下，可能是时间获取函数的网页有时候不稳定导致出现问题

**Comment by Sexbabe** [comment]
> > > > 昨天开始又不能用了，挂在阿里云，报错的日志如下，供大大参考 FC Invoke Start RequestId: t-67189ef0-15924fb2-05e7b7600086 已设置为随机步数（20000-29999） 2024-10-23T07:02:11.548Z t-67189ef0-15924fb2-05e7b7600086 [ERROR] { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2596c305f8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] } FC Invoke End RequestId: t-67189ef0-15924fb2-05e7b7600086, Error: Unhandled function error
> > > 
> > > 
> > > 我这边这两天跑的都还是正常的哈，可以再去阿里云手动运行一次看看是否成功
> > 
> > 
> > 回大大 我也是同上代码错误 不知道什么情况 刚刚部署并测试的 { "errorMessage": "HTTPConnectionPool(host='worldtimeapi.org', port=80): Max retries exceeded with url: /api/timezone/Asia/Shanghai (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b702f4550>: Failed to establish a new connection: [Errno 101] Network is unreachable',))", "errorType": "ConnectionError", "stackTrace": [ [ "File "/code/index.py"", "line 170", "in main_handler", "push += main(user_list[line], passwd_list[line], step) + '\n'" ], [ "File "/code/index.py"", "line 103", "in main", "t = get_time()" ], [ "File "/code/index.py"", "line 138", "in get_time", "response = requests.get(url, headers=headers).json()" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 75", "in get", "return request('get', url, params=params, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/api.py"", "line 61", "in request", "return session.request(method=method, url=url, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 529", "in request", "resp = self.send(prep, **send_kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/sessions.py"", "line 645", "in send", "r = adapter.send(request, **kwargs)" ], [ "File "/var/fc/lang/python3/lib/python3.6/site-packages/requests/adapters.py"", "line 519", "in send", "raise ConnectionError(e, request=request)" ] ] }
> 
> 我今天下午6点跑了一下还是正常的哈，可以多跑几次试一下，可能是时间获取函数的网页有时候不稳定导致出现问题

嗯刚刚重复试了几次 成功了 但是打开app是同步不了 请教一下是有什么问题呢 但是在app里是有显示步数的只不过 不是在主页面上显示 而是隐藏了

**Comment by wskskss** [comment]
运行后，app步数已更新，但是微信运动没有更新，重新关注也不行。

**Comment by EEEugene** [comment]
> 运行后，app步数已更新，但是微信运动没有更新，重新关注也不行。

APP有同步到步数的话就和代码无关了，试试重新绑定/接入 微信、支付宝吧

**Comment by EEEugene** [comment]
后续有问题另开issue吧，别在这个issue下进行提问了，不太方便。
