### ISSUE TITLE
邮箱登录会自动加上+86

### ISSUE THREAD

**Issue by iPriest** [EEEugene/StepNumberChangeSNC#3]
https://api-user.huami.com:443 "POST /registrations/+86yiojvff@gmail.com/tokens HTTP/1.1" 303 0

登陆失败！

**Comment by EEEugene** [comment]
如果用邮箱的话可以试试39行那里改一下，还是比较建议用手机号吧，我这边也没测试过邮箱能不能用

**Comment by EEEugene** [comment]
已解决，可以使用最新代码，可以用邮箱登录
