### ISSUE TITLE
麻烦问下返回码402一般可能是什么情况

### ISSUE THREAD

**Issue by yxy19740** [EEEugene/StepNumberChangeSNC#5]
{"errorCode":1,"errorMessage":"ServiceSuspended","requestId":"cedd62cd-29b2-4ac5-b8e4-8fd98b13aaa3","statusCode":402}

**Comment by EEEugene** [comment]
暂时没遇到过这种情况，多试几次看看？

**Comment by EEEugene** [comment]
更新了一下阿里云的图文教程，你可以按照我那个教程看看，应该没问题

**Comment by guojunyu7** [comment]
現在注冊的小米運動賬號都只能用郵箱注冊，再使用代碼來部署刷步數，好像行不通耶。有什麽優化解決的辦法嗎？

**Comment by EEEugene** [comment]
暂时还没有...

**Comment by EEEugene** [comment]
暂时没有
