### ISSUE TITLE
可否劳烦更新一下阿里云（免费）的图文教程，感谢🙏

### ISSUE THREAD

**Issue by iChoix** [EEEugene/StepNumberChangeSNC#6]
属实是不会变通到阿里云，麻烦更新图文教程

**Comment by EEEugene** [comment]
最近确实比较忙，没时间做教程，可以先用这篇文章来凑合凑合，流程大概差不多https://mp.weixin.qq.com/s/sExOgDi8l8QuXIz_bucE8Q

**Comment by iChoix** [comment]
> 最近确实比较忙，没时间做教程，可以先用这篇文章来凑合凑合，流程大概差不多https://mp.weixin.qq.com/s/sExOgDi8l8QuXIz_bucE8Q

[应用公测](https://fcnext.console.aliyun.com/applications?spm=5176.fcnext.0.0.112c78c8QyKcsy)
[任务](https://fcnext.console.aliyun.com/cn-hangzhou/tasks)
[服务及函数](https://fcnext.console.aliyun.com/cn-hangzhou/services?spm=5176.fcnext.0.0.112c78c8QyKcsy)
高级功能
[监控大盘](https://fcnext.console.aliyun.com/cn-hangzhou/monitoring)
[域名管理](https://fcnext.console.aliyun.com/cn-hangzhou/domains)
[弹性管理](https://fcnext.console.aliyun.com/cn-hangzhou/autoscale-limits)
[层管理](https://fcnext.console.aliyun.com/cn-hangzhou/layers)
更多功能
[审计日志](https://fcnext.console.aliyun.com/cn-hangzhou/action-trails)
[权限助手](https://fcnext.console.aliyun.com/ram-assistant)
相关产品
[Serverless 工作流](https://fnf.console.aliyun.com/)
[Serverless 应用引擎](https://sae.console.aliyun.com/)
[事件总线 EventBridge](https://eventbridge.console.aliyun.com/)
[首页](https://fcnext.console.aliyun.com/)/[服务列表](https://fcnext.console.aliyun.com/cn-hangzhou/services)/[服务 StepNumberChange 详情](https://fcnext.console.aliyun.com/cn-hangzhou/services/StepNumberChange/detail)/[函数管理](https://fcnext.console.aliyun.com/cn-hangzhou/services/StepNumberChange/functions)/函数详情
常用函数[钉钉答疑群](https://help.aliyun.com/document_detail/53087.html)有奖反馈[快速入门 ](https://fcnext.console.aliyun.com/overview?tab=quick-start)[帮助文档](https://help.aliyun.com/product/50980.html)
函数 StepNumberChangeSNC 详情
版本或别名
LATEST
请选择
函数代码
测试函数
触发器管理
函数配置
监控指标
调用日志
实例列表
链路追踪
弹性管理
异步配置
异步任务列表
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 80b6608b-01ff-4b93-96e5-292c99a8eb95
2022-10-22 10:45:34 80b6608b-01ff-4b93-96e5-292c99a8eb95 [ERROR] {'errorMessage': "Handler 'handler' is missing on module 'index'", 'errorType': 'HandlerNotFound', 'stackTrace': ["AttributeError: module 'index' has no attribute 'handler'"]}
FC Invoke End RequestId: 80b6608b-01ff-4b93-96e5-292c99a8eb95, Error: Unhandled function error

**Comment by iChoix** [comment]
> 最近确实比较忙，没时间做教程，可以先用这篇文章来凑合凑合，流程大概差不多https://mp.weixin.qq.com/s/sExOgDi8l8QuXIz_bucE8Q

![image](https://user-images.githubusercontent.com/6520601/197315752-9b146c41-dab3-4edc-84b3-7252fa668382.png)
按照教程设置运行后提示如图，检查了很多遍没有解决，请指点一二

**Comment by EEEugene** [comment]
确实我也没见过这个错误，感觉应该是代码内的错误，检查一下代码账号密码啥的，有时间我看看做个图文教程把

**Comment by iChoix** [comment]
谢谢大佬  账号密码检查过了 也没问题，感谢大佬百忙之中回复。

**Comment by EEEugene** [comment]
大概弄了一下，【腾讯文档】SNC阿里云使用图文教程
https://docs.qq.com/doc/DWk5rTVN1SldEdWNk，我做的过程没遇到你这个问题，你试试我这个图文流程看看有没有问题把

**Comment by iChoix** [comment]
太感谢了 一会就去试。

**Comment by EEEugene** [comment]
感觉是index.main_handler，这个问题，你看看我图文里的第6点就好

**Comment by iChoix** [comment]
按照大佬的建议使用成功了 ，但是推送方面Qmsg好像被封禁的很厉害，机器人好像都不在线。能否在代码中添加pushplus这样的推送接口代码？

**Comment by EEEugene** [comment]
能力有限hhh，我个人是使用Server酱没啥问题，感觉挺好用的

**Comment by iChoix** [comment]
Server酱也是可以的，但是我在代码里面好像没有找到可以修改server的地方，您源代码是Qmsg和tg两种推送方式。可以添加server酱部分代码吗？

**Comment by iChoix** [comment]
qqtalk = 'https://qmsg.zendee.cn/send/KYE?msg=' + "修改步数：" + step + "  " + response[
        'message'] + '&qq=QQ'
    requests.get(qqtalk)
    return result
#修改上方的KYE和QQ
# qqtalk = 'https://qmsg.zendee.cn/send/输入你的kye?msg=' + "修改步数：" + step + "  " + response[
#        'message'] + '&qq=输入你的qq号'

具体到123行这一段 把'https://qmsg.zendee.cn/send/KYE?msg=' 这一段替换成‘https://sctapi.ftqq.com/我的参数.send?title=我的参数’。     

明白 我现在去修改一下，刚刚您的图才刷出来，感谢。

**Comment by EEEugene** [comment]
对的，你去试一下

**Comment by EEEugene** [comment]
好像不必须，没什么大问题，填不填都行

**Comment by xfall15** [comment]
![image](https://user-images.githubusercontent.com/80967984/225238036-453aa124-9714-449f-b438-f6097d786f8e.png)

**Comment by xfall15** [comment]
![image](https://user-images.githubusercontent.com/80967984/225238094-eee896bd-62e3-4873-b36e-92b8cd40c50c.png)
执行失败了，不知道哪里出错了
