### ISSUE TITLE
zfb 貌似失效了？

### ISSUE THREAD

**Issue by mybdye** [EEEugene/StepNumberChangeSNC#9]
wx 还有同步

**Comment by EEEugene** [comment]
好像是，昨天开始我的zfb也不同步了，不知道是不是zfb改政策了还是哪里的原因

**Comment by EEEugene** [comment]
据说是zfb方面把zepp life的接口关了

**Comment by mybdye** [comment]
ok

**Comment by EEEugene** [comment]
更新了邮箱登录，目前zfb、vx都可用

**Comment by mybdye** [comment]
> 

测试了邮箱，两都不同步

**Comment by EEEugene** [comment]
1、看看之前手机的有没有解绑完，把手机的解绑先，取关公众号什么的，zfb也是；
2、登录邮箱的号绑定好zfb那些；
3、我这边今天使用都是没有问题的，代码方面测试过了，检查一下账号那些；

**Comment by lhbill** [comment]
实测还是不行，原来手机登录的都解绑了，账号都彻底注销了
邮箱登录zeep，重新绑定，运行代码后zeep life的步数更新了，但是wx和zfb都没动静

**Comment by EEEugene** [comment]
> 实测还是不行，原来手机登录的都解绑了，账号都彻底注销了 邮箱登录zeep，重新绑定，运行代码后zeep life的步数更新了，但是wx和zfb都没动静

我刚刚又测试了一次，复制所有bushu.py的代码，去到阿里云，然后只修改153和155行的账号密码，可以修改成功，支付宝，vx都有，代码是没问题的，操作步骤问题。

<img src="https://sszblog.oss-cn-shenzhen.aliyuncs.com/img/success.png" >

**Comment by EEEugene** [comment]
【腾讯文档】微信、支付宝步数不同步解决教程 NEW
https://docs.qq.com/doc/DU21TcmRxZ2JHYURm
这个文档看一下，如果他的可以用，那么我的代码也就可以用，可以试一下

**Comment by lhbill** [comment]
> 【腾讯文档】微信、支付宝步数不同步解决教程 NEW
> https://docs.qq.com/doc/DU21TcmRxZ2JHYURm
> 这个文档看一下，如果他的可以用，那么我的代码也就可以用，可以试一下

用它的这个也不行，重新注册zeep life账号也不行
zeep life里面的步数都可以更新，就是不能同步，黑号了？
我完全停用一段时间看看吧……
